### PR TITLE
Add unzip to Docker base image recipe

### LINKED ISSUE #5: Add zip in the docker image
Please consider adding `zip` in the docker image.
Some projects make use of it, instead of `lhasa` (e.g. Dopus5) and it would be great if we could skip the manual step of having to install it before using the image. ;)

### PR DESCRIPTION
**Pull request by apiraino**
This should close #5 

(I didn't yet rebuild the Amiga image but I think it's a safe change)

### CODE REVIEW

**Comment by MBeijer** [comment]
you need to update all the other .docker-files as well @apiraino

**Comment by MBeijer** [comment]
common.docker is never built. ;)

**Comment by apiraino** [comment]
you're right. can we remove / rename the `common.docker` if it's not used?

**Comment by MBeijer** [comment]
I use it for reference to make sure all images are the same. But sure,
could put it in a sub folder

**Comment by apiraino** [comment]
> I use it for reference to make sure all images are the same.

Right, it make sense. On a second thought, if I need to change every `arch` Dockerfile then I think it could make sense to have this change in the `amigadev/docker-base` Dockerfile, doesn't it?

**Comment by MBeijer** [comment]
yup

**Comment by apiraino** [comment]
ok, new PR: https://github.com/AmigaPorts/docker-base/pull/5

(not to mention I had added the wrong pkg in this PR 😅)

**Pull request closed without merging**
